import type { TagId } from "./tags";
import type { TechnologyId } from "./technologies";

export interface Project {
    id: string;
    name: string;
    description?: string;
    startDate: Date;
    endDate?: Date;
    technologies?: readonly TechnologyId[];
    tags?: readonly TagId[];
    repo?: string;
    url?: string;
    image?: string;
}

export const projects = [
    {
        id: "website",
        name: "Website",
        description: "The website you are currently on",
        startDate: new Date("2023-07-21"),
        technologies: ["svelte", "typescript", "tailwind"],
        tags: ["web", "personal"],
        repo: "https://github.com/ttoino/website",
        url: "https://toino.pt",
        image: "/projects/website.png",
    },
    {
        id: "top-commiters",
        name: "Top Commiters",
        description: "The top commiters per country",
        startDate: new Date("2023-05-24"),
        technologies: ["svelte", "typescript", "primer"],
        tags: ["web", "personal"],
        repo: "https://github.com/ttoino/top-commiters",
        url: "https://commits.toino.pt",
        image: "/projects/top-commiters.png",
    },
    {
        id: "jmm",
        name: "Java--",
        description: "A Java compiler written in Java",
        startDate: new Date("2023-03-15"),
        endDate: new Date("2023-05-28"),
        technologies: ["java", "antlr"],
        tags: ["native", "university"],
        repo: "https://github.com/ttoino/feup-c",
    },
    {
        id: "atrellado",
        name: "Atrellado",
        description: "A Trello clone",
        startDate: new Date("2022-09-12"),
        endDate: new Date("2023-03-16"),
        technologies: [
            "laravel",
            "php",
            "postgresql",
            "bootstrap",
            "typescript",
        ],
        tags: ["web", "university"],
        repo: "https://github.com/ttoino/feup-lbaw",
        url: "https://atrellado.toino.pt",
        image: "/projects/atrellado.png",
    },
    {
        id: "center",
        name: "Center",
        description: "A digital online multiplayer board game",
        startDate: new Date("2022-12-20"),
        endDate: new Date("2023-01-17"),
        technologies: ["prolog"],
        tags: ["native", "university", "game"],
        repo: "https://github.com/ttoino/feup-pfl-proj2",
        image: "/projects/center.png",
    },
    {
        id: "aocm",
        name: "Advent of Code Manager",
        description: "A CLI to manage Advent of Code",
        startDate: new Date("2022-07-26"),
        endDate: new Date("2022-12-03"),
        technologies: ["python"],
        tags: ["native", "personal"],
        repo: "https://github.com/ttoino/advent-of-code-manager",
    },
    {
        id: "xaufome",
        name: "Xau Fome",
        description: "A food delivery service",
        startDate: new Date("2022-04-01"),
        endDate: new Date("2022-06-14"),
        technologies: ["php", "javascript", "css"],
        tags: ["web", "university"],
        repo: "https://github.com/ttoino/feup-ltw-proj",
        url: "https://xaufome.toino.pt",
        image: "/projects/xaufome.png",
    },
    {
        id: "latex-previewer",
        name: "LaTeX Previewer",
        description: "A LaTeX previewer",
        startDate: new Date("2022-03-29"),
        endDate: new Date("2022-03-30"),
        technologies: ["html", "css", "javascript"],
        tags: ["web", "personal"],
        repo: "https://github.com/ttoino/latex-previewer",
        url: "https://latex.toino.pt",
        image: "/projects/latex-previewer.png",
    },
    {
        id: "ootb",
        name: "Out of the Breach",
        description: "A turn-based strategy game inspired by Into the Breach",
        startDate: new Date("2021-12-27"),
        endDate: new Date("2022-01-30"),
        technologies: ["java", "lanterna"],
        tags: ["native", "university", "game"],
        repo: "https://github.com/ttoino/feup-ldts-proj",
        image: "/projects/ootb.png",
    },
    {
        id: "proggers",
        name: "Proggers",
        description:
            "A single player game in a discord bot where the player runs away from robots",
        startDate: new Date("2021-03-29"),
        endDate: new Date("2021-03-30"),
        technologies: ["cpp", "typescript"],
        tags: ["native", "discord", "personal", "university", "game"],
        repo: "https://github.com/ttoino/proggers-discord-bot",
        image: "/projects/proggers.png",
    },
    {
        id: "solitaire",
        name: "Solitaire",
        description: "The classic solitaire klondike game",
        startDate: new Date("2020-12-14"),
        endDate: new Date("2021-01-24"),
        technologies: ["python", "pygame"],
        tags: ["native", "university", "game"],
        repo: "https://github.com/ttoino/feup-fpro-solitaire",
        image: "/projects/solitaire.png",
    },
    {
        id: "bruno",
        name: "Bruno",
        description: "A terminal based clone of Uno",
        startDate: new Date("2019"),
        endDate: new Date("2019"),
        technologies: ["java", "firebase", "netty"],
        tags: ["native", "personal", "game"],
        repo: "https://github.com/ttoino/bruno",
    },
    {
        id: "watch-face",
        name: "Custom Watch Face",
        description: "A custom watch face for Wear OS",
        startDate: new Date("2019"),
        endDate: new Date("2019"),
        technologies: ["java", "android"],
        tags: ["wearable", "personal"],
        repo: "https://github.com/ttoino/custom-watch-face",
        image: "/projects/watch-face.png",
    },
    {
        id: "opcwp",
        name: "OnePlus Custom Wallpaper Provider",
        description: "A custom animated wallpaper provider for OnePlus",
        startDate: new Date("2019"),
        endDate: new Date("2019"),
        technologies: ["java", "android"],
        tags: ["mobile", "personal"],
        repo: "https://github.com/ttoino/op-custom-wallpaper-provider",
    },
] as const satisfies readonly Project[];
